### ISSUE TITLE
The categories tab 

### ISSUE THREAD

**Issue by the-martian9** [agora-code-community/pwa_agora_cc_merch#10]
In terms of styling is the Categories nav list item seated between the **sign in** button and the **show cart** button in the navbar meant to be a list item or was it supposed to be button as well?

**Comment by Chingaipe** [comment]
That will be a products catalog of some kind, that will have all the products available on the site. Seeing as to how having an endless scroll on the front page (store front) wont be feasible.

**Comment by the-martian9** [comment]
Cheers
